import type { Metadata } from "next";
import { Inter, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar/Navbar'

const nunito_sans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const [state, setState] = useState(0)
  return (
    <html lang="en">
      <body className={nunito_sans.className}>
      <Navbar></Navbar>
      {children}</body>
    </html>
  )
}
