import type { Metadata } from "next";
import { Inter, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar/Navbar'

const nunito_sans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'FoodEase',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito_sans.className }>
        <div className="flex w-[100%]">
          <Navbar></Navbar>
        </div>
          {children}
      </body>
    </html>
  )
}
